"""Export endpoints for run summaries."""
from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse

from app.core.database import get_run

router = APIRouter()


@router.get("/run/{run_id}.md")
async def export_run_md(run_id: str):
    """Export run summary as Markdown."""
    run = await get_run(run_id)
    if not run:
        raise HTTPException(404, "Run not found")

    metrics = run["metrics"]
    hyperparams = run["hyperparams"]

    md = f"""# AegisML Run Report: {run_id}

## Overview
- **Run ID**: {run_id}
- **Task**: {run['task']}
- **Model Type**: {run['model_type']}
- **Dataset**: {run['dataset_id']}
- **Target Column**: {run['target_column']}
- **Created**: {run['created_at']}

## Hyperparameters
"""
    for k, v in hyperparams.items():
        md += f"- **{k}**: {v}\n"

    md += "\n## Metrics\n"
    for k, v in metrics.items():
        if k not in ("confusion_matrix", "classification_report",
                      "transfer_history", "baseline_history"):
            md += f"- **{k}**: {v}\n"

    if "confusion_matrix" in metrics:
        md += f"\n## Confusion Matrix\n```\n{metrics['confusion_matrix']}\n```\n"

    md += f"""
## Artifacts
- Confusion Matrix: `/runs/{run_id}/artifacts/confusion_matrix.png`
- ROC Curve: `/runs/{run_id}/artifacts/roc_curve.png`
- PR Curve: `/runs/{run_id}/artifacts/pr_curve.png`
- Feature Importance: `/runs/{run_id}/artifacts/feature_importance.png`

---
*Generated by AegisML Suite*
"""
    return PlainTextResponse(content=md, media_type="text/markdown")
